services:
  printarr:
    build: .
    container_name: printarr
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - PORT=${PORT:-6969}
    volumes:
      - ./config:/config
    ports:
      - "${PORT:-6969}:${PORT:-6969}"
    restart: unless-stopped
